# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('primKey', models.AutoField(primary_key=True, serialize=False)),
                ('dataCreating', models.DateField(auto_now_add=True)),
                ('dataLastModifaed', models.DateField(auto_now=True)),
                ('autor', models.CharField(max_length=128)),
                ('textMessage', models.CharField(max_length=1024)),
            ],
        ),
    ]
